# Image to build, QC, and annotate BGCs

FROM ubuntu:latest
MAINTAINER Diego Borges <dborgesrmit@gmail.com>
USER root

# Install few tools using apt-get required to get conda package manager up and running 
RUN apt-get update && apt-get install -y --no-install-recommends \
  software-properties-common \
  wget \
  bzip2 \
  build-essential \
  vim \
  libboost-dev \
  libcairo2-dev \
  curl \
  zip \
  unzip \
#  libzmq3-dev #iperl \
#  libcairo2-dev #iperl \
#	texlive-xetex #for printing pdf SUPER heavy (over 1Gb) for PDFs \
  && apt-get update \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

ENV CONDA_VERSION="5.1.0"  
RUN wget https://repo.continuum.io/archive/Anaconda2-${CONDA_VERSION}-Linux-x86_64.sh && \
	bash Anaconda2-${CONDA_VERSION}-Linux-x86_64.sh -b && \
	rm Anaconda2-${CONDA_VERSION}-Linux-x86_64.sh && \
    export PATH=/root/anaconda2/bin:$PATH  && \
    conda config --set show_channel_urls True && \
    conda config --add channels r && \
	conda config --add channels bioconda && \
    conda config --add channels conda-forge && \
    conda update conda && \
    conda install -y \
    	pip \
	    setuptools \
		nb_conda \
		libgcc \
#		conda-build \
		git \
#		plotly \
#		ipywidgets \
#		autoconf \
#		htslib \
#		cython \
#		nodejs \
		&& \
	conda clean -tipy
	
ENV PATH=/root/anaconda2/bin:$PATH


RUN pip install --no-cache-dir \
#		ipywidgets \
#		pysam \
#		myvariant \
#		mygene \
#		weblogo \
		h5py \
#		wand \
#		rst2pdf \
		argparse \
#		python-louvain \
#		joblib \
#		biopython \
#		pyliftover \
#		nbbrowserpdf \
#		bx-python \
#		numpy-stl \
#		solidpython \
#		jupyter_contrib_nbextensions \
#		jupyter-c-kernel \ 
		jupyterlab 
#		nbpresent
#		&& pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
	
#Get pytorch
#RUN conda install pytorch torchvision -y -c soumith
#Configure jupyter
RUN jupyter notebook --generate-config --allow-root && \
	sed -i "/c.NotebookApp.open_browser/c c.NotebookApp.open_browser = False" /root/.jupyter/jupyter_notebook_config.py \
        && sed -i "/c.NotebookApp.ip/c c.NotebookApp.ip = '*'" /root/.jupyter/jupyter_notebook_config.py \
        && sed -i "/c.NotebookApp.notebook_dir/c c.NotebookApp.notebook_dir = '/root'" /root/.jupyter/jupyter_notebook_config.py \
        && sed -i "/c.NotebookApp.token/c c.NotebookApp.token = 'creatingreality'" /root/.jupyter/jupyter_notebook_config.py \
        && sed -i "/c.NotebookApp.iopub_data_rate_limit/c c.NotebookApp.iopub_data_rate_limit = 10000000" /root/.jupyter/jupyter_notebook_config.py 

#set bash as default shell
ENV SHELL=/bin/bash

#Get Euplotid
# RUN cd /root && git clone -b master --single-branch https://github.com/dborgesr/Euplotid.git
# Set Euplotid as working directory

WORKDIR /root


EXPOSE 80
EXPOSE 8895
EXPOSE 8889
CMD ["jupyter", "lab", "--port=8889", "--no-browser", "--allow-root", "--ip=0.0.0.0"]